
 export const REQUEST_CATAGORIES = 'REQUEST_CATAGORIES';
 export const REQUEST_CATAGORIES_SUCCESS = 'REQUEST_CATAGORIES_SUCCESS';
 export const REQUEST_CATAGORIES_FAILURE = 'REQUEST_CATAGORIES_FAILURE';