
export const REQUEST_INCIDENT_CATAGORIES = 'REQUEST_INCIDENT_CATAGORIES';
export const REQUEST_INCIDENT_CATAGORIES_SUCCESS = 'REQUEST_INCIDENT_CATAGORIES_SUCCESS';
export const REQUEST_INCIDENT_CATAGORIES_FAILURE = 'REQUEST_INCIDENT_CATAGORIES_FAILURE';

export const REQUEST_INCIDENT_DISTRICTS = 'REQUEST_INCIDENT_DISTRICTS';
export const REQUEST_INCIDENT_DISTRICTS_SUCCESS = 'REQUEST_INCIDENT_DISTRICTS_SUCCESS';
export const REQUEST_INCIDENT_DISTRICTS_FAILURE = 'REQUEST_INCIDENT_DISTRICTS_FAILURE';

export const REQUEST_INCIDENT_POLICE_STATIONS = 'REQUEST_INCIDENT_POLICE_STATIONS';
export const REQUEST_INCIDENT_POLICE_STATIONS_SUCCESS = 'REQUEST_INCIDENT_POLICE_STATIONS_SUCCESS';
export const REQUEST_INCIDENT_POLICE_STATIONS_FAILURE = 'REQUEST_INCIDENT_POLICE_STATIONS_FAILURE';

export const REQUEST_INCIDENT_POLLING_STATIONS = 'REQUEST_INCIDENT_POLLING_STATIONS';
export const REQUEST_INCIDENT_POLLING_STATIONS_SUCCESS = 'REQUEST_INCIDENT_POLLING_STATIONS_SUCCESS';
export const REQUEST_INCIDENT_POLLING_STATIONS_FAILURE = 'REQUEST_INCIDENT_POLLING_STATIONS_FAILURE';

export const REQUEST_INCIDENT_WARDS = 'REQUEST_INCIDENT_WARDS';
export const REQUEST_INCIDENT_WARDS_SUCCESS = 'REQUEST_INCIDENT_WARDS_SUCCESS';
export const REQUEST_INCIDENT_WARDS_FAILURE = 'REQUEST_INCIDENT_WARDS_FAILURE';

export const ACTIVE_INCIDENT_GET_DATA_REQUEST = 'ACTIVE_INCIDENT_GET_DATA_REQUEST';
export const ACTIVE_INCIDENT_GET_DATA_SUCCESS = 'ACTIVE_INCIDENT_GET_DATA_SUCCESS';
export const ACTIVE_INCIDENT_GET_DATA_ERROR = 'ACTIVE_INCIDENT_GET_DATA_ERROR';

export const SIGN_IN_REQUEST = 'SIGN_IN_REQUEST';
export const SIGN_IN_REQUEST_SUCCESS = 'SIGN_IN_REQUEST_SUCCESS';
export const SIGN_IN_REQUEST_ERROR = 'SIGN_IN_REQUEST_ERROR';

export const TOGGLE_REMEBER_USER = 'TOGGLE_REMEBER_USER';
export const SIGN_OUT = 'SIGN_OUT';
export const SIGN_OUT_ERROR = 'SIGN_OUT_ERROR';