
export const REQUEST_INCIDENT_CATAGORIES = 'REQUEST_INCIDENT_CATAGORIES';
export const REQUEST_INCIDENT_CATAGORIES_SUCCESS = 'REQUEST_INCIDENT_CATAGORIES_SUCCESS';
export const REQUEST_INCIDENT_CATAGORIES_FAILURE = 'REQUEST_INCIDENT_CATAGORIES_FAILURE';

