# Generated by Django 2.2.6 on 2019-10-30 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        ('custom_auth', '0002_auto_20191023_2311'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlevel',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='auth.Group'),
        ),
    ]
