# Generated by Django 2.2.6 on 2019-10-30 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0006_division_is_default_division'),
    ]

    operations = [
        migrations.AddField(
            model_name='division',
            name='is_hq',
            field=models.BooleanField(default=False),
        ),
    ]
