version: '3'

services:  
  incident_frontend:
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - '3001:80'
    environment:
      - REACT_APP_API_BASE_URL=http://localhost:8001