# Generated by Django 2.2.1 on 2019-08-13 13:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('incidents', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('CREATED', 'Created'), ('GENERIC_UPDATE', 'Generic Update'), ('ATTRIBUTE_CHANGE_REQUESTED', 'Attribute change requested'), ('ATTRIBUTE_CHANGE_APPROVED', 'Attribute change approved'), ('ATTRIBUTE_CHANGED', 'Attribute changed'), ('ATTRIBUTE_CHANGE_REJECTED', 'Attribute change rejected'), ('COMMENTED', 'Commented'), ('OUTCOME_ADDED', 'Outcome added'), ('ENTITY_ASSIGNED', 'Entity assigned'), ('ENTITY_REMOVED', 'Entity removed'), ('ACTION_STARTED', 'Started Action'), ('ACTION_COMPLETED', 'Ended Action')], max_length=50)),
                ('reference_id', models.IntegerField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('affected_attribute', models.CharField(blank=True, choices=[('STATUS', 'Status'), ('SEVERITY', 'Severity'), ('OUTCOME', 'Outcome')], max_length=50, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='incidents.Incident')),
                ('initiator', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('linked_event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='events.Event')),
                ('refered_model_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='contenttypes.ContentType')),
            ],
            options={
                'ordering': ('created_date',),
            },
        ),
    ]
