# Generated by Django 2.2.1 on 2019-05-29 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_auto_20190529_1844'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='channel',
            options={'ordering': ('id',)},
        ),
    ]
