
export const INCIDENT_BASIC_DATA_SUBMIT_REQUEST = 'INCIDENT_FORM_BASIC_DATA_SUBMIT_REQUEST';
export const INCIDENT_BASIC_DATA_SUBMIT_SUCCESS = 'INCIDENT_FORM_BASIC_DATA_SUBMIT_SUCCESS';
export const INCIDENT_BASIC_DATA_SUBMIT_ERROR = 'INCIDENT_FORM_BASIC_DATA_SUBMIT_ERROR';


export const INCIDENT_BASIC_DATA_UPDATE_REQUEST = 'INCIDENT_FORM_BASIC_DATA_UPDATE_REQUEST';
export const INCIDENT_BASIC_DATA_UPDATE_SUCCESS = 'INCIDENT_FORM_BASIC_DATA_UPDATE_SUCCESS';
export const INCIDENT_BASIC_DATA_UPDATE_ERROR = 'INCIDENT_FORM_BASIC_DATA_UPDATE_ERROR';

export const INCIDENT_REPORTER_UPDATE_REQUEST = 'INCIDENT_FORM_REPORTER_UPDATE_REQUEST';
export const INCIDENT_REPORTER_UPDATE_SUCCESS = 'INCIDENT_FORM_REPORTER_UPDATE_SUCCESS';
export const INCIDENT_REPORTER_UPDATE_ERROR = 'INCIDENT_FORM_REPORTER_UPDATE_ERROR';

export const INCIDENT_STEPPER_FORWARD = 'INCIDENT_STEPPER_FORWARD';
export const INCIDENT_STEPPER_BACKWARD = 'INCIDENT_STEPPER_BACKWARD';


export const REQUEST_INCIDENT_CATAGORIES = 'REQUEST_INCIDENT_CATAGORIES';
export const REQUEST_INCIDENT_CATAGORIES_SUCCESS = 'REQUEST_INCIDENT_CATAGORIES_SUCCESS';
export const REQUEST_INCIDENT_CATAGORIES_FAILURE = 'REQUEST_INCIDENT_CATAGORIES_FAILURE';

