
export const INCIDENT_BASIC_DATA_SUBMIT_REQUEST = 'INCIDENT_FORM_BASIC_DATA_SUBMIT_REQUEST';
export const INCIDENT_BASIC_DATA_SUBMIT_SUCCESS = 'INCIDENT_FORM_BASIC_DATA_SUBMIT_SUCCESS';
export const INCIDENT_BASIC_DATA_SUBMIT_ERROR = 'INCIDENT_FORM_BASIC_DATA_SUBMIT_ERROR';


export const INCIDENT_GET_DATA_REQUEST = 'INCIDENT_GET_DATA_REQUEST';
export const INCIDENT_GET_DATA_SUCCESS = 'INCIDENT_GET_DATA_SUCCESS';
export const INCIDENT_GET_DATA_ERROR = 'INCIDENT_GET_DATA_ERROR';


export const INCIDENT_BASIC_DATA_UPDATE_REQUEST = 'INCIDENT_FORM_BASIC_DATA_UPDATE_REQUEST';
export const INCIDENT_BASIC_DATA_UPDATE_SUCCESS = 'INCIDENT_FORM_BASIC_DATA_UPDATE_SUCCESS';
export const INCIDENT_BASIC_DATA_UPDATE_ERROR = 'INCIDENT_FORM_BASIC_DATA_UPDATE_ERROR';

export const INCIDENT_REPORTER_UPDATE_REQUEST = 'INCIDENT_FORM_REPORTER_UPDATE_REQUEST';
export const INCIDENT_REPORTER_UPDATE_SUCCESS = 'INCIDENT_FORM_REPORTER_UPDATE_SUCCESS';
export const INCIDENT_REPORTER_UPDATE_ERROR = 'INCIDENT_FORM_REPORTER_UPDATE_ERROR';

export const INCIDENT_STEPPER_FORWARD = 'INCIDENT_STEPPER_FORWARD';
export const INCIDENT_STEPPER_BACKWARD = 'INCIDENT_STEPPER_BACKWARD';
export const RESET_INCIDENT_FORM = 'RESET_INCIDENT_FORM';

export const INCIDENT_FILE_UPLOAD_REQUEST = 'INCIDENT_FILE_UPLOAD_REQUEST';
export const INCIDENT_FILE_UPLOAD_SUCCESS = 'INCIDENT_FILE_UPLOAD_SUCCESS';
export const INCIDENT_FILE_UPLOAD_ERROR = 'INCIDENT_FILE_UPLOAD_ERROR';

export const PUBLIC_FILE_UPLOAD_REQUEST = 'PUBLIC_FILE_UPLOAD_REQUEST';
export const PUBLIC_FILE_UPLOAD_SUCCESS = 'PUBLIC_FILE_UPLOAD_SUCCESS';
export const PUBLIC_FILE_UPLOAD_ERROR = 'PUBLIC_FILE_UPLOAD_ERROR';

export const SUBMIT_INTERNAL_INCIDENT = 'SUBMIT_INTERNAL_INCIDENT';
export const SUBMIT_INTERNAL_INCIDENT_SUCCESS = 'SUBMIT_INTERNAL_INCIDENT_SUCCESS';
export const SUBMIT_INTERNAL_INCIDENT_ERROR = 'SUBMIT_INTERNAL_INCIDENT_ERROR';

export const UPDATE_INTERNAL_INCIDENT = 'UPDATE_INTERNAL_INCIDENT';
export const UPDATE_INTERNAL_INCIDENT_SUCCESS = 'UPDATE_INTERNAL_INCIDENT_SUCCESS';
export const UPDATE_INTERNAL_INCIDENT_ERROR = 'UPDATE_INTERNAL_INCIDENT_ERROR';