# Generated by Django 2.2.1 on 2019-06-04 14:05

from django.db import migrations, models
import django.db.models.deletion
import src.events.models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='incident_id',
            new_name='incident',
        ),
        migrations.RemoveField(
            model_name='event',
            name='linked_event_id',
        ),
        migrations.AddField(
            model_name='event',
            name='linked_event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='events.Event'),
        ),
        migrations.AlterField(
            model_name='event',
            name='affected_attribute',
            field=models.CharField(blank=True, choices=[(src.events.models.AffectedAttribute('Status'), 'Status'), (src.events.models.AffectedAttribute('Severity'), 'Severity'), (src.events.models.AffectedAttribute('Outcome'), 'Outcome')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
