# Generated by Django 2.2.1 on 2019-06-04 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20190604_1405'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='reference_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
