# Generated by Django 2.2.1 on 2019-06-04 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_auto_20190604_1413'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='intiator',
            new_name='initiator',
        ),
    ]
