"""empty message

Revision ID: 1f19e52ae800
Revises: 89d0ca5bf101
Create Date: 2019-01-16 15:31:51.571896

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1f19e52ae800'
down_revision = '89d0ca5bf101'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('district', sa.Column('province', sa.String(length=1024), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('district', 'province')
    # ### end Alembic commands ###
