"""empty message

Revision ID: 2d45bf9db48b
Revises: 52159bc9dfec
Create Date: 2019-01-16 16:43:10.758131

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2d45bf9db48b'
down_revision = '52159bc9dfec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('category', sa.Column('sn_sub_category', sa.String(length=1024), nullable=True))
    op.add_column('category', sa.Column('sn_top_category', sa.String(length=1024), nullable=True))
    op.add_column('category', sa.Column('tm_sub_category', sa.String(length=1024), nullable=True))
    op.add_column('category', sa.Column('tm_top_category', sa.String(length=1024), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('category', 'tm_top_category')
    op.drop_column('category', 'tm_sub_category')
    op.drop_column('category', 'sn_top_category')
    op.drop_column('category', 'sn_sub_category')
    # ### end Alembic commands ###
