"""empty message

Revision ID: 52159bc9dfec
Revises: 9fbb04cb6304
Create Date: 2019-01-16 16:15:32.383653

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '52159bc9dfec'
down_revision = '9fbb04cb6304'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('policestation', sa.Column('division', sa.String(length=1024), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('policestation', 'division')
    # ### end Alembic commands ###
