"""empty message

Revision ID: 5fe1860ff03b
Revises: 04b3030c6e07
Create Date: 2019-01-16 16:48:36.892032

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5fe1860ff03b'
down_revision = '04b3030c6e07'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('policestation', sa.Column('sn_division', sa.String(length=1024), nullable=True))
    op.add_column('policestation', sa.Column('sn_name', sa.String(length=1024), nullable=True))
    op.add_column('policestation', sa.Column('tm_division', sa.String(length=1024), nullable=True))
    op.add_column('policestation', sa.Column('tm_name', sa.String(length=1024), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('policestation', 'tm_name')
    op.drop_column('policestation', 'tm_division')
    op.drop_column('policestation', 'sn_name')
    op.drop_column('policestation', 'sn_division')
    # ### end Alembic commands ###
