"""empty message

Revision ID: 9fbb04cb6304
Revises: 1f19e52ae800
Create Date: 2019-01-16 16:08:11.942913

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9fbb04cb6304'
down_revision = '1f19e52ae800'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('policestation',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('district_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=1024), nullable=True),
    sa.ForeignKeyConstraint(['district_id'], ['district.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('policestation')
    # ### end Alembic commands ###
