{
 "title": "National Dashboard - Complaints",
 "time": { "from": "now/y", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "FOR THE GIVEN TIME RANGE", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "TOTAL",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "rawSql": "\nselect created_date as \"time\",\ncount(*)\nfrom incidents_incident\nwhere    $__timeFilter(created_date) and incidentType = 'COMPLAINT'\nGROUP BY current_status"
    }
   ]
  },
  {
   "title": "NEW / UNVERIFIED",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 5, "x": 5, "y": 1 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "rawSql": "\nselect created_date as \"time\",\ncount(*)\nfrom incidents_incident\nwhere  current_status = 'NEW' and  $__timeFilter(created_date) and incidentType = 'COMPLAINT'\nGROUP BY current_status"
    }
   ]
  },
  {
   "title": "IN-PROGRESS",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 5, "x": 10, "y": 1 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "rawSql": "\nselect created_date as \"time\",\ncount(*) as value\nfrom incidents_incident\nwhere \n(current_status = 'ACTION_TAKEN' or  \ncurrent_status = 'ACTION_PENDING' or \ncurrent_status = 'ADVICE_PROVIDED' or \ncurrent_status = 'ADVICE_REQESTED' or\ncurrent_status = 'VERIFIED' ) and \n$__timeFilter(created_date) and incidentType = 'COMPLAINT'\n\nGROUP BY id"
    }
   ]
  },
  {
   "title": "CLOSED",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 5, "x": 15, "y": 1 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "rawSql": "\nselect created_date as \"time\",\ncount(CASE WHEN current_status = 'CLOSED'  then 'CLOSED'  end) as 'CLOSED'\nfrom incidents_incident\nwhere $__timeFilter(created_date) and incidentType = 'COMPLAINT'\nGROUP BY current_status"
    }
   ]
  },
  {
   "title": "INVALIDATED",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 1 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "rawSql": "\nselect created_date as \"time\",\ncount(CASE WHEN current_status = 'INVALIDATED'  then 'INVALIDATED'  end) as 'INVALIDATED'\nfrom incidents_incident\nwhere $__timeFilter(created_date) and incidentType = 'COMPLAINT'\nGROUP BY current_status"
    }
   ]
  },
  {
   "title": "VIOLATION OF ELECTION LAW: TOP 5 SUBCATEGORIES",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 6, "w": 9, "x": 0, "y": 4 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "\n\n-- select UNIX_TIMESTAMP(date_time) AS time_sec,subcategory as metric, no_of_incidnets as value\n-- from (select date_time,\n--             category,\n--             subcategory,\n--             count(id) as no_of_incidnets\n--       from real_data\n--       where category = '$category'\n--       group by subcategory\n--       order by no_of_incidnets desc,subcategory desc) a\n-- where $__timeFilter(date_time) and (no_of_incidnets*100/'$total_incidents')>'$threshold'   and category = '$category'\n-- group by metric\n-- order by value desc, subcategory desc\n\n\n\n-- select UNIX_TIMESTAMP(date_time) AS time_sec,subcategory as metric, no_of_incidnets as value\n-- from (select date_time,\n--             category,\n--             subcategory,\n--             count(id) as no_of_incidnets\n--       from real_data\n      \n--       group by subcategory\n--       order by no_of_incidnets desc,subcategory desc) a\n-- where $__timeFilter(date_time)   \n-- group by metric\n-- order by value desc, subcategory desc limit 5\n\n\n\nSELECT UNIX_TIMESTAMP(incidents_incident.created_date) AS time_sec, CONCAT( code,' | ',sub_category) as metric,count(incidents_incident.id) as value\nfrom incidents_incident INNER JOIN common_category ON\ncommon_category.id = incidents_incident.category\nwhere\n  $__timeFilter(incidents_incident.created_date) and \n  common_category.top_category=\"Violation of election law\" and incidentType = 'COMPLAINT'\nGROUP by code\norder by value desc, code \nlimit 5\n"
    }
   ]
  },
  {
   "title": "VIOLENCE: TOP 5 SUBCATEGORIES",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 6, "w": 9, "x": 9, "y": 4 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "\n\n-- select UNIX_TIMESTAMP(date_time) AS time_sec,subcategory as metric, no_of_incidnets as value\n-- from (select date_time,\n--             category,\n--             subcategory,\n--             count(id) as no_of_incidnets\n--       from real_data\n--       where category = '$category'\n--       group by subcategory\n--       order by no_of_incidnets desc,subcategory desc) a\n-- where $__timeFilter(date_time) and (no_of_incidnets*100/'$total_incidents')>'$threshold'   and category = '$category'\n-- group by metric\n-- order by value desc, subcategory desc\n\n\n\n-- select UNIX_TIMESTAMP(date_time) AS time_sec,subcategory as metric, no_of_incidnets as value\n-- from (select date_time,\n--             category,\n--             subcategory,\n--             count(id) as no_of_incidnets\n--       from real_data\n      \n--       group by subcategory\n--       order by no_of_incidnets desc,subcategory desc) a\n-- where $__timeFilter(date_time)   \n-- group by metric\n-- order by value desc, subcategory desc limit 5\n\n\n\nSELECT UNIX_TIMESTAMP(incidents_incident.created_date) AS time_sec, CONCAT( code,' | ',sub_category) as metric,count(incidents_incident.id) as value\nfrom incidents_incident INNER JOIN common_category ON\ncommon_category.id = incidents_incident.category\nwhere\n  $__timeFilter(incidents_incident.created_date) and \n  common_category.top_category=\"Violence\" and incidentType = 'COMPLAINT'\nGROUP by code\norder by value desc, code \nlimit 5\n"
    }
   ]
  },
  {
   "title": "OTHER CATEGORY",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 4 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "rawSql": "SELECT UNIX_TIMESTAMP(incidents_incident.created_date) AS time_sec, \ncount(incidents_incident.id) \nfrom incidents_incident INNER JOIN common_category ON\ncommon_category.id = incidents_incident.category\nwhere\n  $__timeFilter(incidents_incident.created_date) and \n  common_category.top_category=\"Other\" and incidentType = 'COMPLAINT'\nGROUP by sub_category\nlimit 5\n"
    }
   ]
  },
  {
   "title": "NO. OF INCIDENTS BY SEVERITY LEVEL",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "select\nUNIX_TIMESTAMP(occured_date) as time_sec,\ncount(id),'Low (1-3)' as metric\nfrom \nincidents_incident as ins\nwhere\n  $__timeFilter(occured_date) and  severity<4 and incidentType = 'COMPLAINT'\ngroup by id\n"
    },
    {
     "rawSql": "select\nUNIX_TIMESTAMP(occured_date) as time_sec,\ncount(id),'Medium (4-7)' as metric\nfrom \nincidents_incident as ins\nwhere\n  $__timeFilter(occured_date) and  severity>3 and severity<8 and incidentType = 'COMPLAINT'\ngroup by id\n"
    },
    {
     "rawSql": "select\nUNIX_TIMESTAMP(occured_date) as time_sec,\ncount(id),'High (8-10)' as metric\nfrom \nincidents_incident as ins\nwhere\n  $__timeFilter(occured_date) and  severity>7 and incidentType = 'COMPLAINT'\ngroup by id\n"
    }
   ]
  },
  {
   "title": "NO. OF INCIDENTS BY MODE",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 10 },
   "format": "short",
   "valueName": "total",
   "targets": [
    {
     "rawSql": "-- SELECT\n--   $__timeGroupAlias(date_time,1m),\n--   mode_of_recieve AS metric,\n--   count(mode_of_recieve) AS \"mode_of_recieve\"\n-- FROM real_data \n-- WHERE\n--   $__timeFilter(date_time)\n-- GROUP BY 1,2\n\n\nSELECT\n  $__timeFilter(date_time) as time_sec,\n  mode_of_recieve AS metric,\n  count(mode_of_recieve) AS \"mode_of_recieve\"\nFROM (select occured_date  as date_time , common_channel.name as mode_of_recieve from incidents_incident inner join common_channel on incidents_incident.infoChannel = common_channel.id where\n  $__timeFilter(occured_date) and incidentType = 'COMPLAINT') as real_data\nGROUP BY 1,2"
    }
   ]
  },
  { "title": "ALL INCIDENTS", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "TOTAL",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 16 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "rawSql": "\nselect occured_date as \"time\",\ncount(*)\n--   count(CASE WHEN current_status != 'RESOLVED' then 'Unresolved' end) as Unresolved,\nfrom incidents_incident\n\nwhere incidentType = 'COMPLAINT'\nGROUP BY current_status"
    }
   ]
  },
  {
   "title": "NEW / UNVERIFIED",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 5, "x": 5, "y": 16 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "rawSql": "\nselect occured_date as \"time\",\ncount(CASE WHEN current_status = 'NEW' then 'NEW'  end) as 'NEW'\n--   count(CASE WHEN current_status != 'RESOLVED' then 'Unresolved' end) as Unresolved,\nfrom incidents_incident\nwhere  incidentType = 'COMPLAINT'\nGROUP BY current_status"
    }
   ]
  },
  {
   "title": "IN-PROGRESS",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 5, "x": 10, "y": 16 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "rawSql": "\nselect occured_date as \"time\",\ncount(*) as 'ACTIVE' \n--   count(CASE WHEN current_status != 'RESOLVED' then 'Unresolved' end) as Unresolved,\nfrom incidents_incident\nwhere \n(current_status = 'ACTION_TAKEN' or  \ncurrent_status = 'ACTION_PENDING' or \ncurrent_status = 'ADVICE_PROVIDED' or \ncurrent_status = 'ADVICE_REQESTED' or\ncurrent_status = 'VERIFIED' or\ncurrent_status != 'CLOSED' and\ncurrent_status != 'INVALIDATED' and\ncurrent_status != 'NEW')\nand incidentType = 'COMPLAINT'\n\nGROUP BY current_status"
    }
   ]
  },
  {
   "title": "CLOSED",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 5, "x": 15, "y": 16 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "rawSql": "\nselect occured_date as \"time\",\ncount(CASE WHEN current_status = 'CLOSED'  then 'CLOSED'  end) as 'CLOSED'\nfrom incidents_incident\nwhere  incidentType = 'COMPLAINT'\nGROUP BY current_status"
    }
   ]
  },
  {
   "title": "INVALIDATED",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 16 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "rawSql": "\nselect occured_date as \"time\",\ncount(CASE WHEN current_status = 'INVALIDATED'  then 'INVALIDATED'  end) as 'INVALIDATED'\nfrom incidents_incident\nwhere  incidentType = 'COMPLAINT'\nGROUP BY current_status"
    }
   ]
  }
 ]
}