{
 "title": "National Dashboard - Working",
 "time": { "from": "now/d-8h", "to": "now/d+1d-8h-1d" },
 "refresh": "5s",
 "panels": [
  {
   "title": "INCIDENTS FOR THE GIVEN TIME RANGE",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }
  },
  {
   "title": "TOTAL",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "rawSql": "select created_date as \"time\",\ncount(*)\nfrom incidents_incident\nwhere    $__timeFilter(created_date)\nGROUP BY current_status"
    }
   ]
  },
  {
   "title": "NEW ",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 5, "x": 4, "y": 1 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "rawSql": "\nselect created_date as \"time\",\ncount(*)\nfrom incidents_incident\nwhere  current_status = 'NEW' and  $__timeFilter(created_date)\nGROUP BY current_status"
    }
   ]
  },
  {
   "title": "IN-PROGRESS",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 5, "x": 9, "y": 1 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "rawSql": "\nselect\ncount(*) as value\nfrom incidents_incident\nwhere \n(current_status = 'ACTION_TAKEN' or  \ncurrent_status = 'ACTION_PENDING' or \ncurrent_status = 'ADVICE_PROVIDED' or \ncurrent_status = 'ADVICE_REQESTED' or\ncurrent_status = 'VERIFIED' ) and \n$__timeFilter(created_date)\n\n-- GROUP BY id"
    }
   ]
  },
  {
   "title": "CLOSED",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 5, "x": 14, "y": 1 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "rawSql": "select created_date as \"time\",\ncount(*)\nfrom incidents_incident\nwhere (current_status = 'CLOSED' || current_status =  'INVALIDATED') and $__timeFilter(created_date)\nGROUP BY current_status"
    }
   ]
  },
  {
   "title": "UN-ASSIGNED",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 5, "x": 19, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "\nselect T.Total - ( T.VERIFIED + T.NEW + T.INVALIDATED + T.CLOSED + T.ADVICE_REQESTED + T.ACTION_TAKEN + T.ACTION_PENDING ) as val\nfrom\n(select   created_date as \"time\", \n sum(( CASE WHEN  current_status  = 'VERIFIED' THEN 1 ELSE 0 END) ) As 'VERIFIED',\nSUM(( CASE WHEN current_status = 'NEW' THEN 1 ELSE 0 END )) AS 'NEW',\nSUM( CASE WHEN current_status = 'INVALIDATED' THEN 1 ELSE 0 END ) AS 'INVALIDATED',\nSUM( CASE WHEN current_status = 'CLOSED' THEN 1 ELSE 0 END ) AS 'CLOSED',\nSUM( CASE WHEN current_status = 'ADVICE_REQESTED' THEN 1 ELSE 0  END ) AS 'ADVICE_REQESTED',\nSUM( CASE WHEN current_status = 'ACTION_TAKEN' THEN 1 ELSE 0  END ) AS 'ACTION_TAKEN',\nSUM( CASE WHEN current_status = 'ACTION_PENDING' THEN 1 ELSE 0  END ) AS 'ACTION_PENDING', \nSUM( CASE WHEN current_status = 'ADVICE_PROVIDED' THEN 1 ELSE 0  END ) AS 'ADVICE_PROVIDED',\ncount(*) as 'Total' \nfrom incidents_incident where $__timeFilter(created_date) ) as T \n\n\n-- from incidents_incident\n-- where (current_status is null || category = '') and $__timeFilter(created_date)\n-- where (current_status != 'VERIFIED' || current_status != 'NEW' || current_status != 'INVALIDATED' || current_status != 'CLOSED' || current_status != 'ADVICE_REQESTED' || current_status != 'ACTION_TAKEN' || current_status != 'ACTION_PENDING') and $__timeFilter(created_date)\n-- GROUP BY current_status"
    }
   ]
  },
  {
   "title": "VIOLATION OF ELECTION LAW: TOP 5 SUBCATEGORIES",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 6, "w": 9, "x": 0, "y": 4 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "\n\n-- select UNIX_TIMESTAMP(date_time) AS time_sec,subcategory as metric, no_of_incidnets as value\n-- from (select date_time,\n--             category,\n--             subcategory,\n--             count(id) as no_of_incidnets\n--       from real_data\n--       where category = '$category'\n--       group by subcategory\n--       order by no_of_incidnets desc,subcategory desc) a\n-- where $__timeFilter(date_time) and (no_of_incidnets*100/'$total_incidents')>'$threshold'   and category = '$category'\n-- group by metric\n-- order by value desc, subcategory desc\n\n\n\n-- select UNIX_TIMESTAMP(date_time) AS time_sec,subcategory as metric, no_of_incidnets as value\n-- from (select date_time,\n--             category,\n--             subcategory,\n--             count(id) as no_of_incidnets\n--       from real_data\n      \n--       group by subcategory\n--       order by no_of_incidnets desc,subcategory desc) a\n-- where $__timeFilter(date_time)   \n-- group by metric\n-- order by value desc, subcategory desc limit 5\n\n\n\nSELECT UNIX_TIMESTAMP(incidents_incident.created_date) AS time_sec, CONCAT( code,' | ',sub_category) as metric,count(incidents_incident.id) as value\nfrom incidents_incident INNER JOIN common_category ON\ncommon_category.id = incidents_incident.category\nwhere\n  $__timeFilter(incidents_incident.created_date) and \n  common_category.top_category=\"Violation of election law\"\nGROUP by code\norder by value desc, code \nlimit 5\n"
    }
   ]
  },
  {
   "title": "VIOLENCE: TOP 5 SUBCATEGORIES",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 6, "w": 9, "x": 9, "y": 4 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "\n\n-- select UNIX_TIMESTAMP(date_time) AS time_sec,subcategory as metric, no_of_incidnets as value\n-- from (select date_time,\n--             category,\n--             subcategory,\n--             count(id) as no_of_incidnets\n--       from real_data\n--       where category = '$category'\n--       group by subcategory\n--       order by no_of_incidnets desc,subcategory desc) a\n-- where $__timeFilter(date_time) and (no_of_incidnets*100/'$total_incidents')>'$threshold'   and category = '$category'\n-- group by metric\n-- order by value desc, subcategory desc\n\n\n\n-- select UNIX_TIMESTAMP(date_time) AS time_sec,subcategory as metric, no_of_incidnets as value\n-- from (select date_time,\n--             category,\n--             subcategory,\n--             count(id) as no_of_incidnets\n--       from real_data\n      \n--       group by subcategory\n--       order by no_of_incidnets desc,subcategory desc) a\n-- where $__timeFilter(date_time)   \n-- group by metric\n-- order by value desc, subcategory desc limit 5\n\n\n\nSELECT UNIX_TIMESTAMP(incidents_incident.created_date) AS time_sec, CONCAT( code,' | ',sub_category) as metric,count(incidents_incident.id) as value\nfrom incidents_incident INNER JOIN common_category ON\ncommon_category.id = incidents_incident.category\nwhere\n  $__timeFilter(incidents_incident.created_date) and \n  common_category.top_category=\"Violence\"\nGROUP by code\norder by value desc, code \nlimit 5\n"
    }
   ]
  },
  {
   "title": "NO. OF INCIDENTS BY MODE",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 11, "w": 6, "x": 18, "y": 4 },
   "format": "short",
   "valueName": "total",
   "targets": [
    {
     "rawSql": "-- SELECT\n--   $__timeGroupAlias(date_time,1m),\n--   mode_of_recieve AS metric,\n--   count(mode_of_recieve) AS \"mode_of_recieve\"\n-- FROM real_data \n-- WHERE\n--   $__timeFilter(date_time)\n-- GROUP BY 1,2\n\n\nSELECT\n  $__timeFilter(date_time) as time_sec,\n  mode_of_recieve AS metric,\n  count(mode_of_recieve) AS \"mode_of_recieve\"\nFROM (select occured_date  as date_time , common_channel.name as mode_of_recieve from incidents_incident inner join common_channel on incidents_incident.infoChannel = common_channel.id where\n  $__timeFilter(occured_date)) as real_data\nGROUP BY 1,2"
    }
   ]
  },
  {
   "title": "NO. OF INCIDENTS BY SEVERITY LEVEL",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "select\nUNIX_TIMESTAMP(occured_date) as time_sec,\ncount(id),'Low (1-3)' as metric\nfrom \nincidents_incident as ins\nwhere\n  $__timeFilter(occured_date) and  severity<4\ngroup by id\n"
    },
    {
     "rawSql": "select\nUNIX_TIMESTAMP(occured_date) as time_sec,\ncount(id),'Medium (4-7)' as metric\nfrom \nincidents_incident as ins\nwhere\n  $__timeFilter(occured_date) and  severity>3 and severity<8\ngroup by id\n"
    },
    {
     "rawSql": "select\nUNIX_TIMESTAMP(occured_date) as time_sec,\ncount(id),'High (8-10)' as metric\nfrom \nincidents_incident as ins\nwhere\n  $__timeFilter(occured_date) and  severity>7\ngroup by id\n"
    }
   ]
  },
  {
   "title": "OTHER CATEGORY",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 12, "y": 10 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "rawSql": "SELECT now() as 'time',\ncount(incidents_incident.id) \nfrom incidents_incident INNER JOIN common_category ON\ncommon_category.id = incidents_incident.category\nwhere\n  $__timeFilter(incidents_incident.created_date) and incidents_incident.category = NULL -- OR incidents_incident.category =\"\"\n  -- and common_category.top_category=\"NULL\"\n-- GROUP by sub_category\n\n"
    }
   ]
  },
  {
   "title": "UN-ASSIGNED MODE",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 15, "y": 10 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "select now() as 'time',count(*) as value\n--   count(CASE WHEN current_status != 'RESOLVED' then 'Unresolved' end) as Unresolved,\nfrom incidents_incident\nwhere \n  ( category is null or category = '' )\n  AND \n  $__timeFilter(created_date)"
    }
   ]
  },
  {
   "title": "INCIDENTS ASSIGNED TO THE POLICE STATION FOR THE GIVEN TIME RANGE",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 }
  },
  {
   "title": "TOTAL",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 16 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "SELECT count(eew.is_action_completed) as value,\neew.created_date as 'time'\n\n FROM incidents_escalateexternalworkflow eew\n inner join incidents_incident ins on ins.id = eew.incident_id\n inner join auth_user au on au.id = eew.escalated_user_id\n inner join auth_group ag on ag.id = au.id \n inner join auth_user_groups aug on au.id = aug.group_id \n  where aug.group_id  in (2,8,9 ) and $__timeFilter(eew.created_date)\n\n"
    }
   ]
  },
  {
   "title": "ACTION PENDING",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 16 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "SELECT \nsum(( CASE WHEN  eew.is_action_completed  = '0' THEN 1 ELSE 0 END) ) As value, eew.created_date as 'time'\n\n  FROM incidents_escalateexternalworkflow eew\n inner join incidents_incident ins on ins.id = eew.incident_id\n inner join auth_user au on au.id = eew.escalated_user_id\n inner join auth_group ag on ag.id = au.id \n inner join auth_user_groups aug on au.id = aug.group_id \n  where aug.group_id  in (2,8,9 ) and $__timeFilter(eew.created_date)"
    }
   ]
  },
  {
   "title": "ACTION TAKEN",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 16 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "SELECT \nsum(( CASE WHEN  eew.is_action_completed  = '1' THEN 1 ELSE 0 END) ) As value,\neew.created_date as 'time'\n FROM incidents_escalateexternalworkflow eew\n inner join incidents_incident ins on ins.id = eew.incident_id\n inner join auth_user au on au.id = eew.escalated_user_id\n inner join auth_group ag on ag.id = au.id \n inner join auth_user_groups aug on au.id = aug.group_id \n  where aug.group_id  in (2,8,9 ) and $__timeFilter(eew.created_date)\n  "
    }
   ]
  },
  {
   "title": "Percentage ",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 16 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "rawSql": " SELECT SUM(T1.Tot-T1.Police) AS Others , T1.Police , now() as 'time' FROM (\n Select ((SELECT count(eew.is_action_completed) as value\n\n FROM incidents_escalateexternalworkflow eew\n inner join incidents_incident ins on ins.id = eew.incident_id\n inner join auth_user au on au.id = eew.escalated_user_id\n inner join auth_group ag on ag.id = au.id  -- and ag.id = 2\n inner join auth_user_groups aug on au.id = aug.group_id  -- and aug.group_id = 2\n -- inner join auth_group ag on ag.id = aug.group_id = 2\n  where aug.group_id  in (2,8,9 )  and $__timeFilter(eew.created_date) ))as Police,\n  \n (select count(*) \n from incidents_incident\n where current_status != 'NULL' and $__timeFilter(created_date)) as Tot ) AS T1\n"
    }
   ]
  },
  {
   "title": "ALL TIME ASSIGNED TO THE POLICE STATION",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 }
  },
  {
   "title": "TOTAL",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 21 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "SELECT count(eew.is_action_completed) as value\n\n FROM incidents_escalateexternalworkflow eew\n inner join incidents_incident ins on ins.id = eew.incident_id\n inner join auth_user au on au.id = eew.escalated_user_id\n inner join auth_group ag on ag.id = au.id  -- and ag.id = 2\n inner join auth_user_groups aug on au.id = aug.group_id  -- and aug.group_id = 2\n -- inner join auth_group ag on ag.id = aug.group_id = 2\n  where aug.group_id  in (2,8,9 ) \n"
    }
   ]
  },
  {
   "title": "ACTION PENDING",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 21 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "SELECT \nsum(( CASE WHEN  eew.is_action_completed  = '0' THEN 1 ELSE 0 END) ) As value\n\n FROM incidents_escalateexternalworkflow eew\n inner join incidents_incident ins on ins.id = eew.incident_id\n inner join auth_user au on au.id = eew.escalated_user_id\n inner join auth_group ag on ag.id = au.id  -- and ag.id = 2\n inner join auth_user_groups aug on au.id = aug.group_id  -- and aug.group_id = 2\n -- inner join auth_group ag on ag.id = aug.group_id = 2\n  where aug.group_id  in (2,8,9 ) "
    }
   ]
  },
  {
   "title": "ACTION TAKEN",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 21 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "SELECT \nsum(( CASE WHEN  eew.is_action_completed  = '1' THEN 1 ELSE 0 END) ) As value\n\n FROM incidents_escalateexternalworkflow eew\n inner join incidents_incident ins on ins.id = eew.incident_id\n inner join auth_user au on au.id = eew.escalated_user_id\n inner join auth_group ag on ag.id = au.id  -- and ag.id = 2\n inner join auth_user_groups aug on au.id = aug.group_id  -- and aug.group_id = 2\n -- inner join auth_group ag on ag.id = aug.group_id = 2\n  where aug.group_id  in (2,8,9 ) \n"
    }
   ]
  },
  {
   "title": "Percentage ",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 21 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "rawSql": " SELECT SUM(T1.Tot-T1.Police) AS Others , T1.Police , now() as 'time' FROM (\n Select ((SELECT count(eew.is_action_completed) as value\n\n FROM incidents_escalateexternalworkflow eew\n inner join incidents_incident ins on ins.id = eew.incident_id\n inner join auth_user au on au.id = eew.escalated_user_id\n inner join auth_group ag on ag.id = au.id  -- and ag.id = 2\n inner join auth_user_groups aug on au.id = aug.group_id  -- and aug.group_id = 2\n -- inner join auth_group ag on ag.id = aug.group_id = 2\n  where aug.group_id  in (2,8,9 )  and $__timeFilter(eew.created_date) ))as Police,\n  \n (select count(*) \n from incidents_incident\n where current_status != 'NULL' -- and $__timeFilter(created_date)\n ) as Tot ) AS T1\n"
    }
   ]
  },
  { "title": "ALL INCIDENTS", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "TOTAL",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 26 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "rawSql": "select count(*) as val\nfrom incidents_incident"
    }
   ]
  },
  {
   "title": "NEW ",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 6, "y": 26 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "rawSql": "select count(*) as val\nfrom incidents_incident\nwhere  current_status = 'NEW'\nGROUP BY current_status"
    }
   ]
  },
  {
   "title": "IN-PROGRESS",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 5, "x": 10, "y": 26 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "rawSql": "select count(*) as value\nfrom incidents_incident\nwhere \n(current_status = 'ACTION_TAKEN' or  \ncurrent_status = 'ACTION_PENDING' or \ncurrent_status = 'ADVICE_PROVIDED' or \ncurrent_status = 'ADVICE_REQESTED' or\ncurrent_status = 'VERIFIED' )  "
    }
   ]
  },
  {
   "title": "CLOSED",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 5, "x": 15, "y": 26 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "rawSql": "select count(*)\nfrom incidents_incident\nwhere (current_status = 'CLOSED' || current_status =  'INVALIDATED')\n-- GROUP BY current_status"
    }
   ]
  },
  {
   "title": "UN-ASSIGNED",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 26 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "rawSql": "\nselect T.Total - ( T.VERIFIED + T.NEW + T.INVALIDATED + T.CLOSED + T.ADVICE_REQESTED + T.ACTION_TAKEN + T.ACTION_PENDING ) as val\nfrom\n(select   created_date as \"time\", \n sum(( CASE WHEN  current_status  = 'VERIFIED' THEN 1 ELSE 0 END) ) As 'VERIFIED',\nSUM(( CASE WHEN current_status = 'NEW' THEN 1 ELSE 0 END )) AS 'NEW',\nSUM( CASE WHEN current_status = 'INVALIDATED' THEN 1 ELSE 0 END ) AS 'INVALIDATED',\nSUM( CASE WHEN current_status = 'CLOSED' THEN 1 ELSE 0 END ) AS 'CLOSED',\nSUM( CASE WHEN current_status = 'ADVICE_REQESTED' THEN 1 ELSE 0  END ) AS 'ADVICE_REQESTED',\nSUM( CASE WHEN current_status = 'ACTION_TAKEN' THEN 1 ELSE 0  END ) AS 'ACTION_TAKEN',\nSUM( CASE WHEN current_status = 'ACTION_PENDING' THEN 1 ELSE 0  END ) AS 'ACTION_PENDING', \nSUM( CASE WHEN current_status = 'ADVICE_PROVIDED' THEN 1 ELSE 0  END ) AS 'ADVICE_PROVIDED',\ncount(*) as 'Total' \nfrom incidents_incident ) as T "
    }
   ]
  }
 ]
}