{
 "title": "Parliamentary Election 2020",
 "time": { "from": "now-1y", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   { "name": "election", "label": "Election", "query": "PE20" },
   { "name": "incidentType", "label": "Incident Type", "query": "COMPLAINT" },
   { "name": "archive_status", "label": "Archive Status", "query": "CLOSED, INVALIDATED" },
   {
    "name": "hq_users",
    "label": "HQ Users",
    "query": "select au.id from auth_user au left join custom_auth_profile ap  on au.id = ap.user_id where au.is_active = true and ap.division_id =  (select id from custom_auth_division where is_default_division = true)"
   },
   { "name": "hq_entry_user", "label": "HQ Entry User", "query": "71" }
  ]
 },
 "panels": [
  { "title": "FOR THE GIVEN TIME RANGE", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "TOTAL",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "rawSql": "SELECT\n   created_date as \"time\", count(created_date)\nFROM incidents_incident\nWHERE $__timeFilter(created_date) and incidentType = '$incidentType' and election = '$election'\n  and created_by_id IN ($hq_entry_user)\n"
    }
   ]
  },
  {
   "title": "IN-PROGRESS",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 1 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "rawSql": "SELECT\n  created_date as \"time\", count(created_date)\nFROM incidents_incident\nWHERE $__timeFilter(created_date) and incidentType = '$incidentType' and election = '$election'\n  and current_status NOT IN ('CLOSED', 'INVALIDATED')\n  and created_by_id IN ($hq_entry_user)\n\n"
    }
   ]
  },
  {
   "title": "CLOSED",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 5, "x": 12, "y": 1 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "rawSql": "SELECT\n  created_date as \"time\", count(created_date)\nFROM incidents_incident\nWHERE $__timeFilter(created_date) and incidentType = '$incidentType' and election = '$election'\n  and current_status IN ('CLOSED', 'INVALIDATED')\n  and created_by_id IN ($hq_entry_user)\n\n"
    }
   ]
  },
  {
   "title": "MAP",
   "type": "grafana-worldmap-panel",
   "gridPos": { "h": 18, "w": 7, "x": 17, "y": 1 },
   "valueName": "total",
   "targets": [
    {
     "rawSql": "SELECT d.name as name, d.lat as lat , d.lon as lon , count(district) as value\n  from incidents_incident ins\n  inner join common_district d on d.code = ins.district\n  where lat is not null and $__timeFilter(ins.created_date)\n  and ins.created_by_id IN ($hq_entry_user)\n  group by ins.district\n-- ORDER BY d.created_date"
    }
   ]
  },
  {
   "title": "BY SEVERITY",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 5, "w": 9, "x": 0, "y": 5 },
   "format": "locale",
   "valueName": "total",
   "targets": [
    {
     "rawSql": "select\nUNIX_TIMESTAMP(created_date) as time_sec,\ncount(id),'Low (1-3)' as metric\nfrom \nincidents_incident as ins\nwhere\n  $__timeFilter(created_date) and  severity<4 and incidentType = '$incidentType' and election = '$election'\n  and created_by_id IN ($hq_entry_user)\ngroup by id\n"
    },
    {
     "rawSql": "select\nUNIX_TIMESTAMP(created_date) as time_sec,\ncount(id),'Medium (4-7)' as metric\nfrom \nincidents_incident as ins\nwhere\n  $__timeFilter(created_date) and  severity>3 and severity<8 and incidentType = '$incidentType' and election = '$election'\n  and created_by_id IN ($hq_entry_user)\ngroup by id\n"
    },
    {
     "rawSql": "select\nUNIX_TIMESTAMP(created_date) as time_sec,\ncount(id),'High (8-10)' as metric\nfrom \nincidents_incident as ins\nwhere\n  $__timeFilter(created_date) and  severity>7 and incidentType = '$incidentType' and election = '$election'\n  and created_by_id IN ($hq_entry_user)\ngroup by id\n"
    }
   ]
  },
  {
   "title": "VIOLENCE vs VIOLATION OF LAW vs OTHER",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 5, "w": 8, "x": 9, "y": 5 },
   "format": "locale",
   "valueName": "total",
   "targets": [
    {
     "rawSql": "select\nUNIX_TIMESTAMP(created_date) as time_sec,\ncount(id),'Violence' as metric\nfrom \nincidents_incident as ins\nwhere\n  $__timeFilter(created_date) and incidentType = '$incidentType' and election = '$election'\n  and category IN (select id from common_category where top_category = 'Violence')\n  and created_by_id IN ($hq_entry_user)\ngroup by id\n"
    },
    {
     "rawSql": "select\nUNIX_TIMESTAMP(created_date) as time_sec,\ncount(id),'Violation of election law' as metric\nfrom \nincidents_incident as ins\nwhere\n  $__timeFilter(created_date) and incidentType = '$incidentType' and election = '$election'\n  and category IN (select id from common_category where top_category = 'Violation of election law')\n  and created_by_id IN ($hq_entry_user)\ngroup by id\n"
    },
    {
     "rawSql": "select\nUNIX_TIMESTAMP(created_date) as time_sec,\ncount(id),'Other' as metric\nfrom \nincidents_incident as ins\nwhere\n  $__timeFilter(created_date) and incidentType = '$incidentType' and election = '$election'\n  and category IN (select id from common_category where top_category = 'Other')\n  and created_by_id IN ($hq_entry_user)\ngroup by id\n"
    }
   ]
  },
  {
   "title": "BY DISTRICT",
   "type": "graph",
   "gridPos": { "h": 9, "w": 17, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT d.code as metrics, count(d.name) as value , ins.created_date as time\n  \n  from incidents_incident ins\n  inner join common_district d on d.code = ins.district\n  where lat is not null and $__timeFilter(ins.created_date)\n  and created_by_id IN ($hq_entry_user)\n  group by ins.district\n-- ORDER BY d.created_date"
    }
   ]
  },
  {
   "title": "ALL INCIDENTS",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "collapsed": true
  },
  {
   "title": "TOTAL",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 20 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "rawSql": "SELECT count(created_date)\nFROM incidents_incident\nWHERE incidentType = '$incidentType' and election = '$election'\n\n"
    }
   ]
  },
  {
   "title": "IN-PROGRESS",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 20 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "rawSql": "SELECT count(created_date)\nFROM incidents_incident\nWHERE  incidentType = '$incidentType' and election = '$election'\nand current_status NOT IN ('CLOSED', 'INVALIDATED')\n\n"
    }
   ]
  },
  {
   "title": "CLOSED",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 20 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "rawSql": "SELECT  count(created_date)\nFROM incidents_incident\nWHERE incidentType = '$incidentType' and election = '$election'\nand current_status IN ('CLOSED', 'INVALIDATED')\n\n"
    }
   ]
  }
 ]
}