# Generated by Django 2.2.1 on 2019-09-11 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_auto_20190911_1119'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='order',
            field=models.IntegerField(null=True, unique=True),
        ),
    ]
