# Generated by Django 2.2.1 on 2019-06-05 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0005_auto_20190605_0934'),
        ('common', '0002_auto_20190605_0934'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PolllingStation',
            new_name='PollingStation',
        ),
    ]
