# Generated by Django 2.2.1 on 2019-09-11 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_auto_20190911_1145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='order',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
