# Generated by Django 2.2.1 on 2019-09-22 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0007_auto_20190922_0356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='district',
            name='code',
            field=models.CharField(max_length=36, unique=True),
        ),
        migrations.AlterField(
            model_name='dsdivision',
            name='code',
            field=models.CharField(max_length=36, unique=True),
        ),
        migrations.AlterField(
            model_name='gndivision',
            name='code',
            field=models.CharField(default='DEFAULT', max_length=36, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='policestation',
            name='code',
            field=models.CharField(max_length=36, unique=True),
        ),
        migrations.AlterField(
            model_name='pollingstation',
            name='code',
            field=models.CharField(default='DEFAULT', max_length=36, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ward',
            name='code',
            field=models.CharField(default='DEFAULT', max_length=36, unique=True),
            preserve_default=False,
        ),
    ]
