# Generated by Django 2.2.1 on 2019-10-10 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0011_province'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='code',
            field=models.CharField(default='ADD_NEW_CODE', max_length=36, unique=True),
            preserve_default=False,
        ),
    ]
