# Generated by Django 2.2.1 on 2019-06-04 19:00

from django.conf import settings
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('refId', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('occurrence', models.CharField(blank=True, choices=[('OCCURRED', 'Occurred'), ('OCCURRING', 'Occurring'), ('WILL_OCCUR', 'Will Occur')], max_length=50, null=True)),
                ('election', models.CharField(max_length=200)),
                ('infoChannel', models.CharField(blank=True, max_length=200, null=True)),
                ('current_status', models.CharField(blank=True, choices=[('NEW', 'New'), ('CLOSED', 'Closed'), ('ACTION_TAKEN', 'Action Taken'), ('ACTION_PENDING', 'Action Pending'), ('ADVICE_PROVIDED', 'Advice Provided'), ('ADVICE_REQESTED', 'Advice Requested'), ('VERIFIED', 'Verified')], max_length=50, null=True)),
                ('previous_status', models.CharField(blank=True, choices=[('NEW', 'New'), ('CLOSED', 'Closed'), ('ACTION_TAKEN', 'Action Taken'), ('ACTION_PENDING', 'Action Pending'), ('ADVICE_PROVIDED', 'Advice Provided'), ('ADVICE_REQESTED', 'Advice Requested'), ('VERIFIED', 'Verified')], max_length=50, null=True)),
                ('current_severity', models.CharField(blank=True, choices=[('CRITICAL', 'Critical'), ('MAJOR', 'Major'), ('MODERATE', 'Moderate'), ('MINOR', 'Minor'), ('INSIGNIFICANT', 'Insignificant'), ('DEFAULT', 'Default')], max_length=50, null=True)),
                ('previous_severity', models.CharField(blank=True, choices=[('CRITICAL', 'Critical'), ('MAJOR', 'Major'), ('MODERATE', 'Moderate'), ('MINOR', 'Minor'), ('INSIGNIFICANT', 'Insignificant'), ('DEFAULT', 'Default')], max_length=50, null=True)),
                ('hasPendingStatusChange', models.BooleanField()),
                ('location', models.CharField(blank=True, max_length=200, null=True)),
                ('address', models.CharField(blank=True, max_length=200, null=True)),
                ('coordinates', models.CharField(blank=True, max_length=200, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('assignees', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('created_date',),
            },
        ),
    ]
