# Generated by Django 2.2.1 on 2019-06-18 16:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_auto_20190605_1130'),
        ('incidents', '0011_auto_20190618_1402'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='common.District'),
        ),
        migrations.AddField(
            model_name='incident',
            name='police_station',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='common.PoliceStation'),
        ),
    ]
