# Generated by Django 2.2.1 on 2019-06-27 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0015_auto_20190618_1734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='election',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='incident',
            name='refId',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
