# Generated by Django 2.2.1 on 2019-08-13 13:57

from django.db import migrations, models
import django.db.models.deletion
import functools
import src.file_upload.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('incidents', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to=functools.partial(src.file_upload.models._update_filename, *(), **{'path': ''}))),
                ('extension', models.CharField(default='no_ext', max_length=20)),
                ('remark', models.CharField(max_length=200, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='incidents.Incident')),
            ],
            options={
                'ordering': ('created_date',),
            },
        ),
    ]
