# Generated by Django 2.2.1 on 2019-08-27 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_upload', '0002_auto_20190827_1654'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='original_name',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
    ]
