# Generated by Django 2.2.1 on 2019-07-16 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_upload', '0002_auto_20190702_1737'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file',
            old_name='created_date',
            new_name='timestamp',
        ),
        migrations.RemoveField(
            model_name='file',
            name='incident',
        ),
        migrations.RemoveField(
            model_name='file',
            name='name',
        ),
        migrations.RemoveField(
            model_name='file',
            name='original_name',
        ),
        migrations.AddField(
            model_name='file',
            name='remark',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(upload_to=''),
        ),
    ]
