# Generated by Django 2.2.1 on 2019-07-16 09:46

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0019_auto_20190702_1653'),
        ('file_upload', '0003_auto_20190716_0736'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='file',
            options={'ordering': ('created_date',)},
        ),
        migrations.RenameField(
            model_name='file',
            old_name='timestamp',
            new_name='created_date',
        ),
        migrations.AddField(
            model_name='file',
            name='incident',
            field=models.ForeignKey(default='4a2f68f577094b539c6b3f2fe595e02f', on_delete=django.db.models.deletion.DO_NOTHING, to='incidents.Incident'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='file',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
