# Generated by Django 2.2.1 on 2019-07-16 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_upload', '0004_auto_20190716_0946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='remark',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
