# Generated by Django 2.2.1 on 2019-07-16 15:48

from django.db import migrations, models
import functools
import src.file_upload.models


class Migration(migrations.Migration):

    dependencies = [
        ('file_upload', '0005_auto_20190716_1000'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='extension',
            field=models.CharField(default='no_ext', max_length=20),
        ),
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(upload_to=functools.partial(src.file_upload.models._update_filename, *(), **{'path': ''})),
        ),
    ]
