
export const REQUEST_INCIDENT_EVENT_TRAIL = 'REQUEST_INCIDENT_EVENT_TRAIL';
export const REQUEST_INCIDENT_EVENT_TRAIL_SUCCESS = 'REQUEST_INCIDENT_EVENT_TRAIL_SUCCESS';
export const REQUEST_INCIDENT_EVENT_TRAIL_ERROR = 'REQUEST_INCIDENT_EVENT_TRAIL_ERROR';

export const POST_INCIDENT_COMMENT = 'POST_INCIDENT_COMMENT';
export const POST_INCIDENT_COMMENT_SUCCESS = 'POST_INCIDENT_COMMENT_SUCCESS';
export const POST_INCIDENT_COMMENT_ERROR = 'POST_INCIDENT_COMMENT_ERROR';

export const CHANGE_INCIDENT_STATUS = 'CHANGE_INCIDENT_STATUS';
export const CHANGE_INCIDENT_STATUS_SUCCESS = 'CHANGE_INCIDENT_STATUS_SUCCESS';
export const CHANGE_INCIDENT_STATUS_ERROR = 'CHANGE_INCIDENT_STATUS_ERROR';

export const CHANGE_INCIDENT_SEVERITY = 'CHANGE_INCIDENT_SEVERITY';
export const CHANGE_INCIDENT_SEVERITY_SUCCESS = 'CHANGE_INCIDENT_SEVERITY_SUCCESS';
export const CHANGE_INCIDENT_SEVERITY_ERROR = 'CHANGE_INCIDENT_SEVERITY_ERROR';