
export const REQUEST_INCIDENT_EVENT_TRAIL = 'REQUEST_INCIDENT_EVENT_TRAIL';
export const REQUEST_INCIDENT_EVENT_TRAIL_SUCCESS = 'REQUEST_INCIDENT_EVENT_TRAIL_SUCCESS';
export const REQUEST_INCIDENT_EVENT_TRAIL_FAILURE = 'REQUEST_INCIDENT_EVENT_TRAIL_FAILURE';

export const POST_INCIDENT_EVENT_TRAIL = 'POST_INCIDENT_EVENT_TRAIL';
export const POST_INCIDENT_EVENT_TRAIL_SUCCESS = 'POST_INCIDENT_EVENT_TRAIL_SUCCESS';
export const POST_INCIDENT_EVENT_TRAIL_FAILURE = 'POST_INCIDENT_EVENT_TRAIL_FAILURE';