export const REQUEST_INCIDENT_EVENT_TRAIL = "REQUEST_INCIDENT_EVENT_TRAIL";
export const REQUEST_INCIDENT_EVENT_TRAIL_SUCCESS =
  "REQUEST_INCIDENT_EVENT_TRAIL_SUCCESS";
export const REQUEST_INCIDENT_EVENT_TRAIL_ERROR =
  "REQUEST_INCIDENT_EVENT_TRAIL_ERROR";

export const POST_INCIDENT_COMMENT = "POST_INCIDENT_COMMENT";
export const POST_INCIDENT_COMMENT_SUCCESS = "POST_INCIDENT_COMMENT_SUCCESS";
export const POST_INCIDENT_COMMENT_ERROR = "POST_INCIDENT_COMMENT_ERROR";

export const CHANGE_INCIDENT_STATUS = "CHANGE_INCIDENT_STATUS";
export const CHANGE_INCIDENT_STATUS_SUCCESS = "CHANGE_INCIDENT_STATUS_SUCCESS";
export const CHANGE_INCIDENT_STATUS_ERROR = "CHANGE_INCIDENT_STATUS_ERROR";

export const CHANGE_INCIDENT_SEVERITY = "CHANGE_INCIDENT_SEVERITY";
export const CHANGE_INCIDENT_SEVERITY_SUCCESS =
  "CHANGE_INCIDENT_SEVERITY_SUCCESS";
export const CHANGE_INCIDENT_SEVERITY_ERROR = "CHANGE_INCIDENT_SEVERITY_ERROR";

export const RESOLVE_EVENT_APPROVAL = "RESOLVE_EVENT_APPROVAL";
export const RESOLVE_EVENT_APPROVAL_SUCCESS = "RESOLVE_EVENT_APPROVAL_SUCCESS";
export const RESOLVE_EVENT_APPROVAL_ERROR = "RESOLVE_EVENT_APPROVAL_ERROR";

export const REQUEST_ALL_INCIDENTS = "REQUEST_ALL_INCIDENTS";
export const REQUEST_ALL_INCIDENTS_SUCCESS = "REQUEST_ALL_INCIDENTS_SUCCESS";
export const REQUEST_ALL_INCIDENTS_ERROR = "REQUEST_ALL_INCIDENTS_ERROR";

export const REQUEST_ALL_USERS = "REQUEST_ALL_USERS";
export const REQUEST_ALL_USERS_SUCCESS = "REQUEST_ALL_USERS_SUCCESS";
export const REQUEST_ALL_USERS_ERROR = "REQUEST_ALL_USERS_ERROR";

export const UPDATE_INCIDENT_ASSIGNEE = "UPDATE_INCIDENT_ASSIGNEE";
export const UPDATE_INCIDENT_ASSIGNEE_SUCCESS =
  "UPDATE_INCIDENT_ASSIGNEE_SUCCESS";
export const UPDATE_INCIDENT_ASSIGNEE_ERROR = "UPDATE_INCIDENT_ASSIGNEE_ERROR";

export const INCIDENT_SEARCH_FILTERS_UPDATE = "INCIDENT_SEARCH_FILTERS_UPDATE";
export const INCIDENT_SEARCH_FILTERS_RESET = "INCIDENT_SEARCH_FILTERS_RESET";
