# Generated by Django 2.2.1 on 2019-08-13 13:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('refId', models.CharField(blank=True, max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('occurrence', models.CharField(blank=True, choices=[('OCCURRED', 'Occurred'), ('OCCURRING', 'Occurring'), ('WILL_OCCUR', 'Will Occur')], max_length=50, null=True)),
                ('election', models.CharField(blank=True, max_length=200)),
                ('polling_station', models.CharField(blank=True, max_length=200, null=True)),
                ('ds_division', models.CharField(blank=True, max_length=200, null=True)),
                ('ward', models.CharField(blank=True, max_length=200, null=True)),
                ('category', models.CharField(blank=True, max_length=200, null=True)),
                ('police_station', models.CharField(blank=True, max_length=200, null=True)),
                ('di_division', models.CharField(blank=True, max_length=200, null=True)),
                ('police_division', models.CharField(blank=True, max_length=200, null=True)),
                ('district', models.CharField(blank=True, max_length=200, null=True)),
                ('province', models.CharField(blank=True, max_length=200, null=True)),
                ('infoChannel', models.CharField(blank=True, max_length=200, null=True)),
                ('hasPendingStatusChange', models.CharField(blank=True, default='F', max_length=1)),
                ('hasPendingSeverityChange', models.CharField(blank=True, default='T', max_length=1)),
                ('location', models.CharField(blank=True, max_length=200, null=True)),
                ('address', models.CharField(blank=True, max_length=200, null=True)),
                ('coordinates', models.CharField(blank=True, max_length=200, null=True)),
                ('complainer_consent', models.BooleanField(blank=True, default=False, null=True)),
                ('response_time', models.IntegerField(default=12)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='incident_asignees', to=settings.AUTH_USER_MODEL)),
                ('linked_individuals', models.ManyToManyField(blank=True, related_name='incident_linked_individuals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('created_date',),
                'permissions': (('can_change_assignee', 'Can directly change assignee'),),
            },
        ),
        migrations.CreateModel(
            name='Reporter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('sn_name', models.CharField(blank=True, max_length=200, null=True)),
                ('tm_name', models.CharField(blank=True, max_length=200, null=True)),
                ('reporter_type', models.CharField(blank=True, max_length=200, null=True)),
                ('email', models.CharField(blank=True, max_length=200, null=True)),
                ('telephone', models.CharField(blank=True, max_length=200, null=True)),
                ('address', models.CharField(blank=True, max_length=200, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='IncidentStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_status', models.CharField(blank=True, choices=[('NEW', 'New'), ('CLOSED', 'Closed'), ('ACTION_TAKEN', 'Action Taken'), ('ACTION_PENDING', 'Action Pending'), ('ADVICE_PROVIDED', 'Advice Provided'), ('ADVICE_REQESTED', 'Advice Requested'), ('VERIFIED', 'Verified')], max_length=50, null=True)),
                ('current_status', models.CharField(choices=[('NEW', 'New'), ('CLOSED', 'Closed'), ('ACTION_TAKEN', 'Action Taken'), ('ACTION_PENDING', 'Action Pending'), ('ADVICE_PROVIDED', 'Advice Provided'), ('ADVICE_REQESTED', 'Advice Requested'), ('VERIFIED', 'Verified')], max_length=50)),
                ('approved', models.BooleanField(default=False)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='incidents.Incident')),
            ],
            options={
                'ordering': ('id',),
                'permissions': (('can_change_status', 'Can directly change status'), ('can_request_status_change', 'Can request to change status'), ('can_approve_status_change', 'Can approve a status change request'), ('can_reject_status_change', 'Can reject a status change request')),
            },
        ),
        migrations.CreateModel(
            name='IncidentSeverity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_severity', models.CharField(blank=True, choices=[('CRITICAL', 'Critical'), ('MAJOR', 'Major'), ('MODERATE', 'Moderate'), ('MINOR', 'Minor'), ('INSIGNIFICANT', 'Insignificant'), ('DEFAULT', 'Default')], max_length=50, null=True)),
                ('current_severity', models.CharField(choices=[('CRITICAL', 'Critical'), ('MAJOR', 'Major'), ('MODERATE', 'Moderate'), ('MINOR', 'Minor'), ('INSIGNIFICANT', 'Insignificant'), ('DEFAULT', 'Default')], max_length=50)),
                ('approved', models.BooleanField(default=False)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='incidents.Incident')),
            ],
            options={
                'ordering': ('id',),
                'permissions': (('can_change_severity', 'Can directly change severity'), ('can_request_severity_change', 'Can request to change severity'), ('can_approve_severity_change', 'Can approve a severity change request'), ('can_reject_severity_change', 'Can reject a severity change request')),
            },
        ),
        migrations.CreateModel(
            name='IncidentPoliceReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nature_of_incident', models.CharField(blank=True, max_length=200, null=True)),
                ('complainers_name', models.CharField(blank=True, max_length=200, null=True)),
                ('complainers_address', models.CharField(blank=True, max_length=200, null=True)),
                ('victims_name', models.CharField(blank=True, max_length=200, null=True)),
                ('victims_address', models.CharField(blank=True, max_length=200, null=True)),
                ('respondents_name', models.CharField(blank=True, max_length=200, null=True)),
                ('respondents_address', models.CharField(blank=True, max_length=200, null=True)),
                ('no_of_vehicles_arrested', models.IntegerField(blank=True, default=0, null=True)),
                ('steps_taken', models.CharField(blank=True, max_length=200, null=True)),
                ('court_case_no', models.CharField(blank=True, max_length=200, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='incidents.Incident')),
            ],
            options={
                'ordering': ('created_date',),
            },
        ),
        migrations.CreateModel(
            name='IncidentComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('is_outcome', models.BooleanField(default=False)),
                ('sn_body', models.CharField(blank=True, max_length=200)),
                ('tm_body', models.CharField(blank=True, max_length=200)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='incidents.Incident')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('id',),
            },
        ),
        migrations.AddField(
            model_name='incident',
            name='reporter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='incidents.Reporter'),
        ),
    ]
