# Generated by Django 2.2.1 on 2019-06-05 07:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IncidentSeverity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_severity', models.CharField(choices=[('CRITICAL', 'Critical'), ('MAJOR', 'Major'), ('MODERATE', 'Moderate'), ('MINOR', 'Minor'), ('INSIGNIFICANT', 'Insignificant'), ('DEFAULT', 'Default')], max_length=50)),
                ('current_severity', models.CharField(choices=[('CRITICAL', 'Critical'), ('MAJOR', 'Major'), ('MODERATE', 'Moderate'), ('MINOR', 'Minor'), ('INSIGNIFICANT', 'Insignificant'), ('DEFAULT', 'Default')], max_length=50)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='IncidentStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_status', models.CharField(choices=[('NEW', 'New'), ('CLOSED', 'Closed'), ('ACTION_TAKEN', 'Action Taken'), ('ACTION_PENDING', 'Action Pending'), ('ADVICE_PROVIDED', 'Advice Provided'), ('ADVICE_REQESTED', 'Advice Requested'), ('VERIFIED', 'Verified')], max_length=50)),
                ('current_status', models.CharField(choices=[('NEW', 'New'), ('CLOSED', 'Closed'), ('ACTION_TAKEN', 'Action Taken'), ('ACTION_PENDING', 'Action Pending'), ('ADVICE_PROVIDED', 'Advice Provided'), ('ADVICE_REQESTED', 'Advice Requested'), ('VERIFIED', 'Verified')], max_length=50)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='Reporter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('refId', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('occurrence', models.CharField(blank=True, choices=[('OCCURRED', 'Occurred'), ('OCCURRING', 'Occurring'), ('WILL_OCCUR', 'Will Occur')], max_length=50, null=True)),
                ('election', models.CharField(max_length=200)),
                ('infoChannel', models.CharField(blank=True, max_length=200, null=True)),
                ('hasPendingStatusChange', models.BooleanField(default=False)),
                ('hasPendingSeverityChange', models.BooleanField(default=False)),
                ('location', models.CharField(blank=True, max_length=200, null=True)),
                ('address', models.CharField(blank=True, max_length=200, null=True)),
                ('coordinates', models.CharField(blank=True, max_length=200, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('assignees', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='common.Category')),
                ('current_severity', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='incidents.IncidentSeverity')),
                ('current_status', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='incidents.IncidentStatus')),
                ('ds_division', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='common.DSDivision')),
                ('polling_station', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='common.PolllingStation')),
                ('reporter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='incidents.Reporter')),
                ('ward', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='common.Ward')),
            ],
            options={
                'ordering': ('created_date',),
            },
        ),
    ]
