# Generated by Django 2.2.1 on 2019-08-25 19:28

from django.db import migrations, models
import src.incidents.models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0002_auto_20190821_1437'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='refId',
            field=models.CharField(default="REFID", max_length=200),
        ),
    ]
