# Generated by Django 2.2.1 on 2019-06-05 07:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0002_auto_20190605_0741'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incident',
            name='current_severity',
        ),
        migrations.RemoveField(
            model_name='incident',
            name='current_status',
        ),
        migrations.AddField(
            model_name='incidentseverity',
            name='incident',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, to='incidents.Incident'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='incidentstatus',
            name='incident',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, to='incidents.Incident'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='incident',
            name='assignees',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='incidentseverity',
            name='previous_severity',
            field=models.CharField(blank=True, choices=[('CRITICAL', 'Critical'), ('MAJOR', 'Major'), ('MODERATE', 'Moderate'), ('MINOR', 'Minor'), ('INSIGNIFICANT', 'Insignificant'), ('DEFAULT', 'Default')], max_length=50),
        ),
        migrations.AlterField(
            model_name='incidentstatus',
            name='previous_status',
            field=models.CharField(blank=True, choices=[('NEW', 'New'), ('CLOSED', 'Closed'), ('ACTION_TAKEN', 'Action Taken'), ('ACTION_PENDING', 'Action Pending'), ('ADVICE_PROVIDED', 'Advice Provided'), ('ADVICE_REQESTED', 'Advice Requested'), ('VERIFIED', 'Verified')], max_length=50),
        ),
    ]
