# Generated by Django 2.2.1 on 2019-08-29 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0003_auto_20190825_1928'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='occcured_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
