# Generated by Django 2.2.1 on 2019-06-05 07:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0003_auto_20190605_0752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='assignees',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
