# Generated by Django 2.2.1 on 2019-08-29 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0004_incident_occcured_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='incident',
            old_name='occcured_date',
            new_name='occured_date',
        ),
    ]
