# Generated by Django 2.2.1 on 2019-08-29 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0005_auto_20190829_1132'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='current_status',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
    ]
