# Generated by Django 2.2.1 on 2019-06-05 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0006_auto_20190605_1153'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='incidentseverity',
            options={'ordering': ('id',), 'permissions': (('can_change_severity', 'Can directly change severity'), ('can_request_severity_change', 'Can request to change severity'), ('can_approve_severity_change', 'Can approve a severity change request'), ('can_reject_severity_change', 'Can reject a severity change request'))},
        ),
        migrations.AlterModelOptions(
            name='incidentstatus',
            options={'ordering': ('id',), 'permissions': (('can_change_status', 'Can directly change status'), ('can_request_status_change', 'Can request to change status'), ('can_approve_status_change', 'Can approve a status change request'), ('can_reject_status_change', 'Can reject a status change request'))},
        ),
    ]
