# Generated by Django 2.2.1 on 2019-08-29 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0006_incident_current_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='incident',
            options={},
        ),
        migrations.AddField(
            model_name='incident',
            name='current_severity',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
    ]
