# Generated by Django 2.2.1 on 2019-08-29 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0007_auto_20190829_1231'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='incident',
            options={'ordering': ('created_date',), 'permissions': (('can_change_assignee', 'Can directly change assignee'),)},
        ),
    ]
