# Generated by Django 2.2.1 on 2019-06-05 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0007_auto_20190605_1154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidentseverity',
            name='previous_severity',
            field=models.CharField(blank=True, choices=[('CRITICAL', 'Critical'), ('MAJOR', 'Major'), ('MODERATE', 'Moderate'), ('MINOR', 'Minor'), ('INSIGNIFICANT', 'Insignificant'), ('DEFAULT', 'Default')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='incidentstatus',
            name='previous_status',
            field=models.CharField(blank=True, choices=[('NEW', 'New'), ('CLOSED', 'Closed'), ('ACTION_TAKEN', 'Action Taken'), ('ACTION_PENDING', 'Action Pending'), ('ADVICE_PROVIDED', 'Advice Provided'), ('ADVICE_REQESTED', 'Advice Requested'), ('VERIFIED', 'Verified')], max_length=50, null=True),
        ),
    ]
