# Generated by Django 2.2.1 on 2019-06-05 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0008_auto_20190605_1244'),
    ]

    operations = [
        migrations.AddField(
            model_name='incidentseverity',
            name='approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='incidentstatus',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
