# Generated by Django 2.2.1 on 2019-09-07 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0008_auto_20190829_1231'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='city',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='grama_niladhari',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='polling_division',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
