# Generated by Django 2.2.1 on 2019-06-18 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0009_auto_20190605_1309'),
    ]

    operations = [
        migrations.RenameField(
            model_name='incident',
            old_name='assignees',
            new_name='linked_individuals',
        ),
    ]
