# Generated by Django 2.2.1 on 2019-09-07 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0009_auto_20190907_1102'),
        ('incidents', '0009_auto_20190907_1144'),
    ]

    operations = [
    ]
