# Generated by Django 2.2.1 on 2019-09-18 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0010_merge_20190907_1246'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='incidentType',
            field=models.CharField(blank=True, choices=[('INQUIRY', 'INQUIRY'), ('COMPLAINT', 'COMPLAINT')], max_length=50, null=True),
        ),
    ]
