# Generated by Django 2.2.1 on 2019-09-18 13:56

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0010_merge_20190907_1246'),
    ]

    operations = [
        migrations.AddField(
            model_name='reporter',
            name='mobile',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='reporter',
            name='unique_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
