# Generated by Django 2.2.1 on 2019-06-18 14:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('incidents', '0010_auto_20190618_1329'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='assignee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='incident_asignees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='incident',
            name='linked_individuals',
            field=models.ManyToManyField(blank=True, related_name='incident_linked_individuals', to=settings.AUTH_USER_MODEL),
        ),
    ]
