# Generated by Django 2.2.1 on 2019-09-18 13:58

from django.db import migrations, models
import src.incidents.models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0011_incident_incidenttype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='incidentType',
            field=models.CharField(choices=[('INQUIRY', 'INQUIRY'), ('COMPLAINT', 'COMPLAINT')], default=src.incidents.models.IncidentType('COMPLAINT'), max_length=50),
        ),
    ]
