# Generated by Django 2.2.1 on 2019-09-18 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0012_auto_20190918_1358'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='proof',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='incidentstatus',
            name='current_status',
            field=models.CharField(choices=[('NEW', 'New'), ('CLOSED', 'Closed'), ('ACTION_TAKEN', 'Action Taken'), ('ACTION_PENDING', 'Action Pending'), ('ADVICE_PROVIDED', 'Advice Provided'), ('ADVICE_REQESTED', 'Advice Requested'), ('VERIFIED', 'Verified'), ('INVALIDATED', 'Invalidated')], max_length=50),
        ),
        migrations.AlterField(
            model_name='incidentstatus',
            name='previous_status',
            field=models.CharField(blank=True, choices=[('NEW', 'New'), ('CLOSED', 'Closed'), ('ACTION_TAKEN', 'Action Taken'), ('ACTION_PENDING', 'Action Pending'), ('ADVICE_PROVIDED', 'Advice Provided'), ('ADVICE_REQESTED', 'Advice Requested'), ('VERIFIED', 'Verified'), ('INVALIDATED', 'Invalidated')], max_length=50, null=True),
        ),
    ]
