# Generated by Django 2.2.1 on 2019-06-18 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0013_auto_20190618_1730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='hasPendingSeverityChange',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='incident',
            name='hasPendingStatusChange',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
