# Generated by Django 2.2.1 on 2019-09-18 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0013_auto_20190918_1415'),
        ('incidents', '0011_auto_20190918_1356'),
    ]

    operations = [
    ]
