# Generated by Django 2.2.1 on 2019-06-18 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0014_auto_20190618_1732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='hasPendingSeverityChange',
            field=models.CharField(blank=True, default='T', max_length=1),
        ),
        migrations.AlterField(
            model_name='incident',
            name='hasPendingStatusChange',
            field=models.CharField(blank=True, default='F', max_length=1),
        ),
    ]
