# Generated by Django 2.2.1 on 2019-09-18 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0014_merge_20190918_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='proof',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
