# Generated by Django 2.2.1 on 2019-09-22 08:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0015_auto_20190918_1517'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='severity',
            field=models.IntegerField(blank=True, default=None, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
    ]
