# Generated by Django 2.2.1 on 2019-06-27 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0016_auto_20190627_1655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidentcomment',
            name='sn_body',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='incidentcomment',
            name='tm_body',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
