# Generated by Django 2.2.1 on 2019-10-03 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0017_auto_20191002_1202'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incident',
            name='reported_through',
        ),
        migrations.AddField(
            model_name='incident',
            name='created_by',
            field=models.CharField(default='OTHER', max_length=50),
        ),
    ]
