# Generated by Django 2.2.1 on 2019-06-30 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0017_auto_20190627_1834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidentcomment',
            name='body',
            field=models.TextField(max_length=200),
        ),
    ]
