# Generated by Django 2.2.1 on 2019-07-02 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0018_auto_20190630_0657'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='incident',
            options={'ordering': ('created_date',), 'permissions': (('can_change_assignee', 'Can directly change assignee'),)},
        ),
    ]
