# Generated by Django 2.2.1 on 2019-10-03 16:28

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0018_auto_20191003_1007'),
    ]

    operations = [
        migrations.CreateModel(
            name='IncidentPerson',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('address', models.CharField(blank=True, max_length=200, null=True)),
                ('political_affliation', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='IncidentVehicle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('vehicle_no', models.CharField(blank=True, max_length=15, null=True)),
                ('is_private', models.BooleanField(default=False)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='incidentpolicereport',
            name='injured_parties',
            field=models.ManyToManyField(blank=True, related_name='incident_injured_parties', to='incidents.IncidentPerson'),
        ),
    ]
