# Generated by Django 2.2.1 on 2019-07-16 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0019_auto_20190702_1653'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='response_time',
            field=models.IntegerField(default=12),
        ),
    ]
