# Generated by Django 2.2.1 on 2019-08-07 15:47

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0020_incident_response_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='complainer_consent',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='IncidentPoliceReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nature_of_incident', models.CharField(blank=True, max_length=200)),
                ('complainers_name', models.CharField(blank=True, max_length=200)),
                ('complainers_address', models.CharField(blank=True, max_length=200)),
                ('victims_name', models.CharField(blank=True, max_length=200)),
                ('victims_address', models.CharField(blank=True, max_length=200)),
                ('respondents_name', models.CharField(blank=True, max_length=200)),
                ('respondents_address', models.CharField(blank=True, max_length=200)),
                ('no_of_vehicles_arrested', models.IntegerField(default=0)),
                ('steps_taken', models.CharField(blank=True, max_length=200)),
                ('court_case_no', models.CharField(blank=True, max_length=200)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='incidents.Incident')),
            ],
            options={
                'ordering': ('created_date',),
            },
        ),
    ]
