# Generated by Django 2.2.1 on 2019-10-06 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0020_auto_20191004_0041'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incidentvehicle',
            name='created_date',
        ),
    ]
