# Generated by Django 2.2.1 on 2019-08-07 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0021_auto_20190807_1547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='complainer_consent',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
