# Generated by Django 2.2.1 on 2019-08-07 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0021_auto_20190807_1547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidentpolicereport',
            name='complainers_address',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='incidentpolicereport',
            name='complainers_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='incidentpolicereport',
            name='court_case_no',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='incidentpolicereport',
            name='nature_of_incident',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='incidentpolicereport',
            name='no_of_vehicles_arrested',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='incidentpolicereport',
            name='respondents_address',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='incidentpolicereport',
            name='respondents_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='incidentpolicereport',
            name='steps_taken',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='incidentpolicereport',
            name='victims_address',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='incidentpolicereport',
            name='victims_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
