# Generated by Django 2.2.1 on 2019-10-10 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0021_remove_incidentvehicle_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidentvehicle',
            name='is_private',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
