# Generated by Django 2.2.1 on 2019-10-10 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0022_auto_20191010_1111'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incidentvehicle',
            name='is_private',
        ),
        migrations.AddField(
            model_name='incidentvehicle',
            name='ownership',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
