# Generated by Django 2.2.1 on 2019-08-12 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0022_auto_20190807_2016'),
        ('incidents', '0022_auto_20190807_2006'),
    ]

    operations = [
    ]
