# Generated by Django 2.2.1 on 2019-08-14 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0023_merge_20190812_0518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidentseverity',
            name='current_severity',
            field=models.IntegerField(blank=True, default=10, null=True),
        ),
        migrations.AlterField(
            model_name='incidentseverity',
            name='previous_severity',
            field=models.IntegerField(blank=True, default=10, null=True),
        ),
    ]
