# Generated by Django 2.2.1 on 2019-10-15 13:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('incidents', '0023_auto_20191010_1113'),
    ]

    operations = [
        migrations.CreateModel(
            name='VerifyWorkflow',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('comment', models.TextField()),
                ('has_proof', models.BooleanField(default=False)),
                ('actioned_user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='incidents_verifyworkflow_related', related_query_name='incidents_verifyworkflows', to=settings.AUTH_USER_MODEL)),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='incidents_verifyworkflow_related', related_query_name='incidents_verifyworkflows', to='incidents.Incident')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
