# Generated by Django 2.2.1 on 2019-08-14 04:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0024_auto_20190814_0434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidentseverity',
            name='current_severity',
            field=models.PositiveIntegerField(default=10, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='incidentseverity',
            name='previous_severity',
            field=models.PositiveIntegerField(default=10, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
    ]
