# Generated by Django 2.2.1 on 2019-10-15 14:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0026_escalateexternalworkflow'),
    ]

    operations = [
        migrations.AlterField(
            model_name='escalateexternalworkflow',
            name='escalated_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='escalation_related', related_query_name='escalated_users', to=settings.AUTH_USER_MODEL),
        ),
    ]
