# Generated by Django 2.2.1 on 2019-10-15 14:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('incidents', '0027_auto_20191015_1442'),
    ]

    operations = [
        migrations.AddField(
            model_name='escalateexternalworkflow',
            name='is_action_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='CompleteActionWorkflow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('comment', models.TextField()),
                ('actioned_user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='incidents_completeactionworkflow_related', related_query_name='incidents_completeactionworkflows', to=settings.AUTH_USER_MODEL)),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='incidents_completeactionworkflow_related', related_query_name='incidents_completeactionworkflows', to='incidents.Incident')),
                ('initiated_workflow', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='incidents.EscalateExternalWorkflow')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
