# Generated by Django 2.2.1 on 2019-10-15 16:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('incidents', '0028_auto_20191015_1457'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestAdviceWorkflow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('comment', models.TextField()),
                ('is_advice_provided', models.BooleanField(default=False)),
                ('actioned_user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='incidents_requestadviceworkflow_related', related_query_name='incidents_requestadviceworkflows', to=settings.AUTH_USER_MODEL)),
                ('assigned_user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='advice_request_related', related_query_name='advice_requested_users', to=settings.AUTH_USER_MODEL)),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='incidents_requestadviceworkflow_related', related_query_name='incidents_requestadviceworkflows', to='incidents.Incident')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProvideAdviceWorkflow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('comment', models.TextField()),
                ('actioned_user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='incidents_provideadviceworkflow_related', related_query_name='incidents_provideadviceworkflows', to=settings.AUTH_USER_MODEL)),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='incidents_provideadviceworkflow_related', related_query_name='incidents_provideadviceworkflows', to='incidents.Incident')),
                ('initiated_workflow', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='incidents.EscalateExternalWorkflow')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
