# Generated by Django 2.2.1 on 2019-10-15 17:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('incidents', '0030_auto_20191015_1643'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvalidateWorkflow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('comment', models.TextField()),
                ('response_time', models.CharField(blank=True, max_length=200, null=True)),
                ('actioned_user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='incidents_invalidateworkflow_related', related_query_name='incidents_invalidateworkflows', to=settings.AUTH_USER_MODEL)),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='incidents_invalidateworkflow_related', related_query_name='incidents_invalidateworkflows', to='incidents.Incident')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EscalateWorkflow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('comment', models.TextField()),
                ('response_time', models.CharField(blank=True, max_length=200, null=True)),
                ('actioned_user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='incidents_escalateworkflow_related', related_query_name='incidents_escalateworkflows', to=settings.AUTH_USER_MODEL)),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='incidents_escalateworkflow_related', related_query_name='incidents_escalateworkflows', to='incidents.Incident')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CloseWorkflow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('assignees', models.TextField()),
                ('entities', models.TextField()),
                ('departments', models.TextField()),
                ('individuals', models.TextField()),
                ('comment', models.TextField()),
                ('actioned_user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='incidents_closeworkflow_related', related_query_name='incidents_closeworkflows', to=settings.AUTH_USER_MODEL)),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='incidents_closeworkflow_related', related_query_name='incidents_closeworkflows', to='incidents.Incident')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AssignUserWorkflow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('actioned_user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='incidents_assignuserworkflow_related', related_query_name='incidents_assignuserworkflows', to=settings.AUTH_USER_MODEL)),
                ('assignee', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='assignee_related', related_query_name='assigned_users', to=settings.AUTH_USER_MODEL)),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='incidents_assignuserworkflow_related', related_query_name='incidents_assignuserworkflows', to='incidents.Incident')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
