# Generated by Django 2.2.1 on 2019-10-15 17:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('incidents', '0031_assignuserworkflow_closeworkflow_escalateworkflow_invalidateworkflow'),
    ]

    operations = [
        migrations.AddField(
            model_name='escalateworkflow',
            name='assignee',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, related_name='escalation_assignee_related', related_query_name='escalation_assigned_users', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
