# Generated by Django 2.2.6 on 2019-10-30 12:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0032_escalateworkflow_assignee'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='incidentstatus',
            options={'ordering': ('id',)},
        ),
        migrations.RemoveField(
            model_name='incident',
            name='hasPendingSeverityChange',
        ),
        migrations.RemoveField(
            model_name='incident',
            name='hasPendingStatusChange',
        ),
        migrations.AlterField(
            model_name='incident',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='IncidentSeverity',
        ),
    ]
