# Generated by Django 2.2.6 on 2020-02-29 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0038_auto_20191107_1706'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='institution',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='letter_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='received_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reporter',
            name='accused_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='reporter',
            name='accused_political_affiliation',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='reporter',
            name='political_affiliation',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
