# Generated by Django 2.2.6 on 2020-02-27 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0038_auto_20191107_1706'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='institution',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='incident',
            name='refId',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
