# Generated by Django 2.2.6 on 2020-03-02 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0040_auto_20200229_2035'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='current_decision',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
    ]
