
export const GET_ALL_INITIAL_INCIDENTS_REQUEST = 'GET_ALL_INITIAL_INCIDENTS_REQUEST';
export const GET_ALL_INITIAL_INCIDENTS_SUCCESS = 'GET_ALL_INITIAL_INCIDENTS_SUCCESS';
export const GET_ALL_INITIAL_INCIDENTS_FAILED = 'GET_ALL_INITIAL_INCIDENTS_FAILED';

