name: Platformer Generated incident-api-eclocal Build
'on':
  push:
    branches:
      - master
jobs:
  build:
    runs-on:
      - ubuntu-latest
    env:
      SERVICE_NAME: ghcr.io/eclk/incidentmanagement
      CONTAINER_REGISTRY: ghcr.io
    steps:
      - uses: actions/checkout@v2
      - name: Set Version
        id: event-version
        run: echo ::set-output name=SOURCE_TAG::${GITHUB_REF#refs/heads/}-${{github.sha}}
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.CONTAINER_REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.DOCKER_PASSWORD_1C2154C6_4CAA_4446_8265_535B5D5D5DCD }}
      - name: Build the Docker image
        run: docker build --tag ${SERVICE_NAME}:ecloal-api-${{steps.event-version.outputs.SOURCE_TAG }} --file ./backend/Dockerfile ./backend/
      - name: GitHub Image Push
        run: docker push $SERVICE_NAME:ecloal-api-${{steps.event-version.outputs.SOURCE_TAG }}
      - name: Platformer Deploy
        uses: platformer-com/build-deploy-action@v1
        with:
          org-id: ${{secrets.ORG_ID_E8AEDE36_3213_4D3A_80FD_C3897CFBBF97}}
          project-id: ${{secrets.PROJECT_ID_E8AEDE36_3213_4D3A_80FD_C3897CFBBF97}}
          token: ${{secrets.AUTOGENERATED_CICD_E8AEDE36_3213_4D3A_80FD_C3897CFBBF97}}
          image-name: ${{env.SERVICE_NAME}}
          tag: ${{steps.event-version.outputs.SOURCE_TAG }}
          container-id: 4c44d277-48e4-4b3b-9f6b-51bd1ce43a2e
